### PR TITLE
add user login code

### PR DESCRIPTION
**Pull request by primecoach619**

### CODE REVIEW

**Comment by primecoach619** [comment]
redo this later

**Comment by primecoach619** [comment]
User login code is complete and ready to be merged with main code base. Adding meladajar as rewiewer

**Comment by primecoach619** [comment]
Reopening - User login code is complete and ready to be merged with main code base. Adding meladajar as rewiewer

**Review by meladajar — COMMENTED** [review]
This looks good! Let's merge it in!

**Pull request merged**
